# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWZ-tMBSyLWALS6M53cpJlriLKFb2y-n
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os
import warnings

data_folder = '/content/drive/MyDrive/PortScan/csv/MachineLearningCVE'

import os
csv_files = [f for f in os.listdir(data_folder) if f.endswith('.csv')]

print(f"✅ Tìm thấy {len(csv_files)} file CSV trong folder:")
for f in sorted(csv_files):
    print("   📄", f)

print("\n🔄 Đang gộp tất cả file CSV...")

combined_df = pd.DataFrame()

for file in csv_files:
    file_path = os.path.join(data_folder, file)
    try:
        df_temp = pd.read_csv(file_path, low_memory=False)
        print(f"Đọc {file}: {df_temp.shape[0]:,} dòng")
        combined_df = pd.concat([combined_df, df_temp], ignore_index=True)
    except Exception as e:
        print(f"Lỗi khi đọc {file}: {e}")

print(f"\n✅ Gộp xong! Tổng: {combined_df.shape[0]:,} dòng, {combined_df.shape[1]} cột")

combined_path = '/content/drive/MyDrive/PortScan/CICIDS2017_Combined.csv'
combined_df.to_csv(combined_path, index=False)
print(f"💾 Đã lưu file gộp tại:\n{combined_path}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GroupShuffleSplit
from sklearn.metrics import classification_report, confusion_matrix
import joblib
import warnings
warnings.filterwarnings('ignore')

# ==================== 1. LOAD MODEL ĐÃ TRAIN SẴN ====================
model_folder = '/content/drive/MyDrive/PortScan/models/'
print("📂 Đang load model đã train...")

rf_model = joblib.load(model_folder + 'rf_final_model.pkl')
scaler = joblib.load(model_folder + 'scaler_final.pkl')
le = joblib.load(model_folder + 'label_encoder.pkl')
features = joblib.load(model_folder + 'feature_list.pkl')

print(f"✅ Model: {type(rf_model).__name__} với {rf_model.n_estimators} cây")
print(f"✅ Số feature: {len(features)}")
print(f"✅ Số lớp: {len(le.classes_)} -> {list(le.classes_)}")

# ==================== 2. LOAD LẠI DỮ LIỆU GỐC ====================
combined_path = '/content/drive/MyDrive/PortScan/CICIDS2017_Combined.csv'
print("\n📂 Đang đọc lại file dữ liệu gốc...")
df = pd.read_csv(combined_path, low_memory=False)
df.columns = df.columns.str.strip()
df['Label'] = df['Label'].astype(str).str.strip()
df = df.drop_duplicates()
print(f"✅ Đọc xong: {df.shape[0]:,} dòng")

X = df[features].copy()
X = X.replace([np.inf, -np.inf], np.nan).fillna(0)
y = df['Label']
y_encoded = le.transform(y)  # dùng transform (không fit lại) để giữ đúng mapping cũ
X_scaled = scaler.transform(X)  # dùng transform (không fit lại) để giữ đúng scale cũ

# ==================== 3. KIỂM TRA 1: OVERFITTING TRÊN TOÀN BỘ DỮ LIỆU ====================
print("\n" + "="*80)
print("🔍 KIỂM TRA 1: SO SÁNH ĐIỂM TRÊN TOÀN BỘ DỮ LIỆU")
print("="*80)
full_score = rf_model.score(X_scaled, y_encoded)
print(f"Accuracy trên TOÀN BỘ dữ liệu (train+test gộp lại): {full_score:.4f}")
print("(Nếu số này gần 1.0 tuyệt đối, có thể model đã 'thuộc lòng' dữ liệu train)")

# ==================== 4. KIỂM TRA 2: TEST TRÊN SPLIT NGẪU NHIÊN MỚI (KHÔNG PHẢI SPLIT LÚC TRAIN) ====================
print("\n" + "="*80)
print("🔍 KIỂM TRA 2: TEST TRÊN 1 RANDOM SPLIT MỚI (random_state khác)")
print("="*80)
_, X_test_r, _, y_test_r = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=999, stratify=y_encoded
)
y_pred_r = rf_model.predict(X_test_r)
print(classification_report(y_test_r, y_pred_r, target_names=le.classes_, digits=4))

# ==================== 5. KIỂM TRA 3: TEST THEO NHÓM (NẾU CÓ CỘT NGÀY/FILE) — QUAN TRỌNG NHẤT ====================
print("\n" + "="*80)
print("🔍 KIỂM TRA 3: TEST THEO NHÓM (mô phỏng dữ liệu HOÀN TOÀN MỚI)")
print("="*80)
group_col_candidates = ['Day', 'day', 'Source File', 'source_file', 'File', 'file', 'Timestamp']
group_col = next((c for c in group_col_candidates if c in df.columns), None)

if group_col:
    groups = df[group_col].values
    gss = GroupShuffleSplit(n_splits=1, test_size=0.3, random_state=7)
    _, test_idx_g = next(gss.split(X_scaled, y_encoded, groups=groups))
    X_test_g, y_test_g = X_scaled[test_idx_g], y_encoded[test_idx_g]

    y_pred_g = rf_model.predict(X_test_g)
    print(f"Test trên nhóm '{group_col}' hoàn toàn tách biệt (model chưa từng thấy nhóm này lúc train gốc):\n")
    print(classification_report(y_test_g, y_pred_g, target_names=le.classes_, digits=4))
else:
    print("⚠️  Không tìm thấy cột nhóm (Day/Source File/Timestamp) trong dữ liệu.")
    print("    Không thể kiểm tra leakage theo nhóm một cách triệt để.")
    print("    Kết quả ở KIỂM TRA 2 vẫn có giá trị tham khảo nhưng KHÔNG loại trừ được leakage.")

# ==================== 6. SO SÁNH VÀ KẾT LUẬN ====================
print("\n" + "="*80)
print("📋 KẾT LUẬN")
print("="*80)
acc_full = full_score
acc_random = (y_pred_r == y_test_r).mean()
print(f"   Accuracy toàn bộ dữ liệu     : {acc_full:.4f}")
print(f"   Accuracy random split mới    : {acc_random:.4f}")
if group_col:
    acc_group = (y_pred_g == y_test_g).mean()
    print(f"   Accuracy split theo nhóm     : {acc_group:.4f}")
    gap = acc_random - acc_group
    if gap > 0.05:
        print(f"\n🚨 CẢNH BÁO: chênh lệch {gap:.4f} giữa random split và group split.")
        print("   -> Model có dấu hiệu bị OVERESTIMATE do data leakage.")
        print("   -> Hiệu năng thực tế khi deploy sẽ gần với con số ở KIỂM TRA 3 hơn.")
    else:
        print(f"\n✅ Chênh lệch nhỏ ({gap:.4f}) -> model có vẻ ổn định, ít bị leakage.")
else:
    if acc_full > 0.999:
        print("\n⚠️  Accuracy trên toàn bộ dữ liệu gần như tuyệt đối (>99.9%).")
        print("   Đây là dấu hiệu ĐÁNG NGỜ cho bài toán network traffic thực tế —")
        print("   nên nghi ngờ có leakage hoặc model bị overfit nặng, dù chưa thể xác nhận")
        print("   100% vì thiếu cột nhóm để kiểm chứng.")
    print("\n👉 Khuyến nghị: tìm cách khôi phục cột Day/Source File trong dữ liệu")
    print("   để có thể kiểm tra leakage một cách chắc chắn.")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, GroupShuffleSplit, cross_val_score
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib
import os
import time
import warnings
warnings.filterwarnings('ignore')

# ==================== 1. ĐỌC DỮ LIỆU ====================
combined_path = '/content/drive/MyDrive/PortScan/CICIDS2017_Combined.csv'
print("📂 Đang đọc file gộp...")
try:
    df = pd.read_csv(combined_path, low_memory=False, encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(combined_path, low_memory=False, encoding='latin1')
df.columns = df.columns.str.strip()

print(f"✅ Đọc xong: {df.shape[0]:,} dòng x {df.shape[1]} cột")

# ---- Làm sạch nhãn (Label thường có khoảng trắng thừa) ----
df['Label'] = df['Label'].astype(str).str.strip()

# ---- Sửa lỗi encoding của dấu gạch ngang đặc biệt trong tên nhãn Web Attack ----
df['Label'] = df['Label'].str.replace('�', '-', regex=False)

# ---- Loại bỏ dòng trùng lặp ----
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"🧹 Đã loại {before - after:,} dòng trùng lặp (còn lại {after:,} dòng)")

# ---- GỘP NHÓM: các loại Web Attack quá ít mẫu (SQL Injection, XSS, Brute Force) ----
# Lý do: từng loại chỉ có vài chục-vài trăm dòng -> không đủ để model học ổn định,
# dẫn đến precision cực thấp (báo động giả tràn lan). Gộp thành 1 nhãn "Web Attack"
# giúp có đủ mẫu để học pattern chung, đổi lại mất khả năng phân biệt loại con.
web_attack_labels = [l for l in df['Label'].unique() if 'Web Attack' in l]
if web_attack_labels:
    print(f"\n🔗 Gộp {len(web_attack_labels)} nhãn Web Attack thành 1 nhóm 'Web Attack':")
    for l in web_attack_labels:
        count = (df['Label'] == l).sum()
        print(f"   - {l}: {count:,} dòng")
    df['Label'] = df['Label'].replace(web_attack_labels, 'Web Attack')

# ==================== 2. XÁC ĐỊNH CỘT DÙNG ĐỂ CHỐNG DATA LEAKAGE ====================
group_col_candidates = ['Day', 'day', 'Source File', 'source_file', 'File', 'file',
                         'Timestamp', 'Flow ID']
group_col = next((c for c in group_col_candidates if c in df.columns), None)

if group_col:
    print(f"\n✅ Tìm thấy cột nhóm '{group_col}' -> sẽ split theo nhóm để chống leakage")
else:
    print("\n⚠️  Không tìm thấy cột ngày/file/timestamp trong dữ liệu.")
    print("    Sẽ dùng random stratified split (KHÔNG chống được leakage triệt để).")
    print("    Khuyến nghị: nếu có thể, thêm lại cột 'Day' hoặc 'Source File' khi gộp CSV.")

# ==================== 3. KẾT HỢP FEATURE (Raw + Derived) ====================
derived_features = [
    'Flow Bytes/s', 'Flow Packets/s',
    'Fwd Packet Length Mean', 'Fwd Packet Length Std',
    'Bwd Packet Length Mean', 'Bwd Packet Length Std',
    'Fwd Packet Length Max', 'Bwd Packet Length Max',
    'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
    'Fwd IAT Mean', 'Fwd IAT Std',
    'Bwd IAT Mean', 'Bwd IAT Std',
    'Down/Up Ratio',
    'Active Mean', 'Active Std',
    'Idle Mean', 'Idle Std',
    'PSH Flag Count', 'SYN Flag Count', 'RST Flag Count'
]

practical_features = [
    'Flow Duration',
    'Total Fwd Packets', 'Total Backward Packets',
    'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
    'Fwd Packet Length Min', 'Bwd Packet Length Min',
    'Fwd IAT Max', 'Fwd IAT Min',
    'Bwd IAT Max', 'Bwd IAT Min',
    'FIN Flag Count', 'ACK Flag Count', 'URG Flag Count',
    'Active Max', 'Active Min',
    'Idle Max', 'Idle Min'
]

all_features = list(dict.fromkeys(derived_features + practical_features))
features = [col for col in all_features if col in df.columns]

missing = [col for col in all_features if col not in df.columns]
if missing:
    print(f"\n⚠️  Các cột sau không tồn tại trong dữ liệu và sẽ bị bỏ qua: {missing}")

print(f"\n✅ Tổng cộng sử dụng {len(features)} feature (Raw + Derived):")
for f in features:
    print("   ✓", f)

# ==================== 4. CHUẨN BỊ DỮ LIỆU ====================
X = df[features].copy()

# ---- Xử lý inf/-inf trước khi fillna ----
n_inf = np.isinf(X.to_numpy(dtype='float64', na_value=0)).sum()
if n_inf > 0:
    print(f"\n⚠️  Phát hiện {n_inf} giá trị vô cực (inf) trong feature — sẽ được thay bằng 0")
X = X.replace([np.inf, -np.inf], np.nan).fillna(0)

y = df['Label']
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print("\nCác lớp tấn công (sau khi gộp Web Attack):")
class_counts = {}
for i, name in enumerate(le.classes_):
    count = (y == name).sum()
    class_counts[name] = count
    warn = " ⚠️ RẤT ÍT MẪU - độ tin cậy thấp dù có SMOTE" if count < 100 else ""
    print(f"   {i}: {name}  ({count:,} dòng){warn}")

# ---- Dùng RobustScaler thay vì StandardScaler ----
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# ==================== 5. SPLIT DỮ LIỆU (CHỐNG DATA LEAKAGE) ====================
if group_col:
    groups = df[group_col].values
    gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(gss.split(X_scaled, y_encoded, groups=groups))
    X_train, X_test = X_scaled[train_idx], X_scaled[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]
else:
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

print(f"\nTrain: {X_train.shape[0]:,} | Test: {X_test.shape[0]:,}")

# ==================== 6. SMOTE — CHỈ ÁP DỤNG TRÊN TẬP TRAIN, SAU KHI ĐÃ SPLIT ====================
# QUAN TRỌNG: SMOTE phải chạy SAU split, chỉ trên X_train/y_train.
# Nếu chạy trước split, dữ liệu giả sinh ra có thể lọt sang test -> data leakage.
#
# Chỉ áp dụng SMOTE cho các lớp "vừa hiếm" (đủ mẫu gốc để nội suy hợp lý, VD > 200
# dòng), KHÔNG áp dụng cho lớp cực hiếm (VD Heartbleed ~11 dòng) vì nội suy từ quá
# ít điểm dữ liệu gốc sẽ tạo ra dữ liệu giả không phản ánh đúng bản chất tấn công.
print("\n🧪 Đang cân bằng dữ liệu train bằng SMOTE (chỉ cho lớp vừa hiếm)...")
try:
    from imblearn.over_sampling import SMOTE

    # Đếm số mẫu mỗi lớp trong tập TRAIN (không phải toàn bộ df)
    unique, counts = np.unique(y_train, return_counts=True)
    train_counts = dict(zip(unique, counts))

    MIN_FOR_SMOTE = 50      # lớp có ít hơn số này -> không đủ tin cậy để SMOTE
    TARGET_SAMPLES = 2000   # số lượng mục tiêu cho các lớp được SMOTE lên

    sampling_strategy = {}
    for cls, cnt in train_counts.items():
        if MIN_FOR_SMOTE <= cnt < TARGET_SAMPLES:
            sampling_strategy[cls] = TARGET_SAMPLES

    if sampling_strategy:
        print("   Các lớp sẽ được SMOTE lên tới ~2000 mẫu:")
        for cls, target in sampling_strategy.items():
            name = le.inverse_transform([cls])[0]
            print(f"   - {name}: {train_counts[cls]:,} -> {target:,}")

        # k_neighbors phải nhỏ hơn số mẫu ít nhất trong nhóm được SMOTE
        min_class_count = min(train_counts[c] for c in sampling_strategy)
        k_neighbors = min(5, min_class_count - 1)

        smote = SMOTE(sampling_strategy=sampling_strategy,
                       k_neighbors=k_neighbors, random_state=42)
        X_train, y_train = smote.fit_resample(X_train, y_train)
        print(f"   ✅ Sau SMOTE: {X_train.shape[0]:,} dòng train "
              f"(tăng thêm {X_train.shape[0] - sum(train_counts.values()):,} dòng giả)")
    else:
        print("   Không có lớp nào đủ điều kiện để SMOTE (quá hiếm hoặc đã đủ nhiều).")

except ImportError:
    print("   ⚠️ Chưa cài thư viện imbalanced-learn. Cài bằng lệnh:")
    print("      !pip install imbalanced-learn -q")
    print("   Bỏ qua SMOTE, tiếp tục train với dữ liệu gốc.")

# ==================== 7. TRAIN MODEL ====================
print("\n🚀 Đang train Random Forest...")
print(f"   Số cây (n_estimators): 120 | Số dòng train: {X_train.shape[0]:,}")
print("   Tiến độ build từng cây sẽ hiện bên dưới (verbose=2):\n")

rf_model = RandomForestClassifier(
    n_estimators=120,
    max_depth=16,
    min_samples_leaf=2,
    n_jobs=-1,
    random_state=42,
    class_weight='balanced',  # nhẹ tay hơn 'balanced_subsample' -> giảm báo động giả
    verbose=2
)

train_start = time.time()
rf_model.fit(X_train, y_train)
train_elapsed = time.time() - train_start
print(f"\n✅ Train xong sau {train_elapsed:.1f} giây ({train_elapsed/60:.1f} phút)")

# ==================== 8. KIỂM TRA OVERFITTING ====================
train_score = rf_model.score(X_train, y_train)
test_score = rf_model.score(X_test, y_test)
print(f"\n📊 Accuracy trên TRAIN: {train_score:.4f}")
print(f"📊 Accuracy trên TEST : {test_score:.4f}")
gap = train_score - test_score
if gap > 0.05:
    print(f"⚠️  Chênh lệch train-test = {gap:.4f} -> có dấu hiệu OVERFITTING."
          f" Cân nhắc giảm max_depth hoặc tăng min_samples_leaf.")
else:
    print(f"✅ Chênh lệch train-test = {gap:.4f} -> chấp nhận được.")

# ==================== 9. ĐÁNH GIÁ CHI TIẾT (TEST) ====================
# Lưu ý: X_test/y_test KHÔNG bị đụng tới bởi SMOTE -> đây vẫn là dữ liệu THẬT 100%,
# nên kết quả đánh giá dưới đây phản ánh đúng hiệu năng thực tế, không bị "ảo" bởi
# dữ liệu giả tạo ra từ SMOTE.
print(f"\n🧪 Đang chạy dự đoán trên tập TEST THẬT (chưa từng qua SMOTE) "
      f"({X_test.shape[0]:,} dòng)...")
test_start = time.time()
y_pred = rf_model.predict(X_test)
test_elapsed = time.time() - test_start
print(f"✅ Dự đoán xong sau {test_elapsed:.2f} giây "
      f"({X_test.shape[0]/test_elapsed:,.0f} dòng/giây)")

print("\n" + "="*80)
print("🎯 KẾT QUẢ MODEL - RAW + DERIVED FEATURES + GỘP NHÓM + SMOTE")
print("="*80)
print(classification_report(y_test, y_pred, target_names=le.classes_, digits=4))

# ---- Confusion matrix chi tiết ----
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm, index=le.classes_, columns=le.classes_)

print("\n" + "="*80)
print("🔍 CONFUSION MATRIX (hàng = thực tế, cột = dự đoán)")
print("="*80)
print(cm_df)

if 'BENIGN' in le.classes_:
    benign_idx = list(le.classes_).index('BENIGN')
    print("\n⚠️  TỶ LỆ TỪNG LOẠI TẤN CÔNG BỊ NHẬN NHẦM THÀNH BENIGN (False Negative):")
    for i, name in enumerate(le.classes_):
        if name == 'BENIGN':
            continue
        total_actual = cm[i].sum()
        missed_as_benign = cm[i][benign_idx]
        if total_actual > 0:
            pct = missed_as_benign / total_actual * 100
            flag = "🚨" if pct > 5 else "  "
            print(f"   {flag} {name}: {missed_as_benign}/{total_actual} ({pct:.2f}%) bị nhận nhầm thành BENIGN")

# ==================== 10. FEATURE IMPORTANCE ====================
importances = pd.Series(rf_model.feature_importances_, index=features).sort_values(ascending=False)
print("\n" + "="*80)
print("📈 TOP 15 FEATURE QUAN TRỌNG NHẤT")
print("="*80)
print(importances.head(15).to_string())

# ==================== 11. LƯU MODEL VÀ KẾT QUẢ ====================
model_folder = '/content/drive/MyDrive/PortScan/models/'
os.makedirs(model_folder, exist_ok=True)

joblib.dump(rf_model, model_folder + 'rf_final_model.pkl')
joblib.dump(scaler, model_folder + 'scaler_final.pkl')
joblib.dump(le, model_folder + 'label_encoder.pkl')
joblib.dump(features, model_folder + 'feature_list.pkl')

cm_df.to_csv(model_folder + 'confusion_matrix.csv')
importances.to_csv(model_folder + 'feature_importance.csv', header=['importance'])

print(f"\n✅ HOÀN TẤT! Model và báo cáo đã lưu tại: {model_folder}")
print("   - rf_final_model.pkl")
print("   - scaler_final.pkl")
print("   - label_encoder.pkl")
print("   - feature_list.pkl")
print("   - confusion_matrix.csv")
print("   - feature_importance.csv")

print("\n" + "="*80)
print("⏱️  TỔNG KẾT THỜI GIAN")
print("="*80)
print(f"   Train model       : {train_elapsed:.1f} giây")
print(f"   Dự đoán trên test : {test_elapsed:.2f} giây")